[indiecinema]
title = "네이버 인디극장 ─ 네이버TV"
url = "https://tv.naver.com/indiecinema/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[siff]
title = "서울독립영화제서울독립영화제 ─ 네이버TV"
url = "https://tv.naver.com/siff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[siwff]
title = "서울국제여성영화제 ─ 네이버TV"
url = "https://tv.naver.com/siwff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[bifan]
title = "부천국제판타스틱영화제 ─ 네이버TV"
url = "https://tv.naver.com/bifanofficial/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[mjff]
title = "무주산골영화제 ─ 네이버TV"
url = "https://tv.naver.com/mjff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[kbs.independentfilm]
title = "독립영화관 ─ 네이버TV"
url = "https://tv.naver.com/kbs.independentfilm/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"

[mbc.video]
title = "출발! 비디오 여행 ─ 네이버TV"
url = "https://tv.naver.com/mbc.video/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
