[navermovie]
title = "네이버 영화 예고편 저장소네이버 영화 ─ 네이버TV"
url = "https://tv.naver.com/navermovie/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[indiecinema]
title = "네이버 인디극장 ─ 네이버TV"
url = "https://tv.naver.com/indiecinema/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[siff]
title = "서울독립영화제서울독립영화제 ─ 네이버TV"
url = "https://tv.naver.com/siff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[siwff]
title = "서울국제여성영화제 ─ 네이버TV"
url = "https://tv.naver.com/siwff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[bifan]
title = "부천국제판타스틱영화제 ─ 네이버TV"
url = "https://tv.naver.com/bifanofficial/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[mjff]
title = "무주산골영화제 ─ 네이버TV"
url = "https://tv.naver.com/mjff/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[kartsmovie]
title = "한국예술종합학교 영화과 ─ 네이버TV"
url = "https://tv.naver.com/kartsmovie/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[mbc-video]
title = "출발! 비디오 여행 ─ 네이버TV"
url = "https://tv.naver.com/mbc.video/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[jtbc-movieroom]
title = "방구석1열 ─ 네이버TV"
url = "https://tv.naver.com/jtbc.movieroom/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"


